### ISSUE TITLE
PayPal PLUS

### ISSUE THREAD

**Issue by bjo3rnf** [extcode/cart_paypal#10]
Hi,

are there any plans on integrating PayPal PLUS into ext:cart?

Thanks in advance.

Cheers
Björn

**Comment by extcode** [comment]
There will be a cart_paypal_plus extension in the next weeks. Currently I'm working on cart version 5.x ans collecting some sponsorship for this new extension.

**Comment by slowhand11** [comment]
Any news about cart_paypal_plus extension?
