### ISSUE TITLE
wrong path in signal slot

### ISSUE THREAD

**Issue by dielobby** [extcode/cart_paypal#11]
There is a wrong path in the signal slot in ext_localconf.php 

It is:
`$dispatcher->connect(
    'Extcode\Cart\Utility\OrderUtility',
    'handlePayment',
    'Extcode\CartPaypal\Service\Payment',
    'handlePayment'
);`
Should be:
`$dispatcher->connect(
    'Extcode\Cart\Utility\PaymentUtility',
    'handlePayment',
    'Extcode\CartPaypal\Service\Payment',
    'handlePayment'
);`

**Comment by extcode** [comment]
Which version of cart you are using? Cart 5.x or 6.x? I'm working on a new version for both releases.

**Comment by dielobby** [comment]
I´m using cart 5.1, cart_products 1.0, cart_paypal 2.2 in TYPO3 8.7

**Comment by extcode** [comment]
I pushed a new branch [3.x](https://github.com/extcode/cart_paypal/tree/3.x) for this cart version.

**Comment by extcode** [comment]
Can I close this issue?
